In [2]:
from google.cloud import bigquery
from sklearn.model_selection import train_test_split
import pandas as pd

In [3]:
client = bigquery.Client()

In [4]:
project_id = client.project
dataset_id = 'iris_test'
table_id = 'iris_data'

In [5]:
project_id

'capable-hash-432501-a6'

In [4]:
table_full_id = f"{project_id}.{dataset_id}.{table_id}"

In [5]:
query = f"SELECT * FROM `{table_full_id}`"

In [6]:
df = client.query(query).to_dataframe()
df

/opt/conda/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2309: UserWarning: Unable to represent RANGE schema as struct using pandas ArrowDtype. Using `object` instead. To use ArrowDtype, use pandas >= 1.5 and pyarrow >= 10.0.1.
  warnings.warn(_RANGE_PYARROW_WARNING)
/opt/conda/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2323: UserWarning: Unable to represent RANGE schema as struct using pandas ArrowDtype. Using `object` instead. To use ArrowDtype, use pandas >= 1.5 and pyarrow >= 10.0.1.
  warnings.warn(_RANGE_PYARROW_WARNING)
/opt/conda/lib/python3.10/site-packages/google/cloud/bigquery/table.py:2337: UserWarning: Unable to represent RANGE schema as struct using pandas ArrowDtype. Using `object` instead. To use ArrowDtype, use pandas >= 1.5 and pyarrow >= 10.0.1.
  warnings.warn(_RANGE_PYARROW_WARNING)

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  target
0                5.1             2.5              3.0             1.1       1
1                5.0             2.0              3.5             1.0       1
2                5.7             2.6              3.5             1.0       1
3                6.0             2.2              4.0             1.0       1
4                5.8             2.6              4.0             1.2       1
..               ...             ...              ...             ...     ...
295              4.7             3.2              1.3             0.2       0
296              5.5             3.5              1.3             0.2       0
297              4.4             3.0              1.3             0.2       0
298              4.4             3.2              1.3             0.2       0
299              5.4             3.9              1.3             0.4       0

[300 rows x 5 columns]

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop("target", axis=1),
    df["target"],
    test_size=0.2,
    random_state=42,
)

In [8]:
X_train

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm
232              6.3             2.9              5.6             1.8
59               5.4             3.9              1.7             0.4
6                6.1             2.8              4.0             1.3
185              5.3             3.7              1.5             0.2
173              6.3             3.3              6.0             2.5
..               ...             ...              ...             ...
188              5.4             3.4              1.5             0.4
71               5.8             2.8              5.1             2.4
106              6.3             2.3              4.4             1.3
270              4.8             3.4              1.6             0.2
102              5.5             2.4              3.7             1.0

[240 rows x 4 columns]

In [9]:
X_train["target"] = y_train
X_test["target"] = y_test

In [10]:
y_train

232    2
59     0
6      1
185    0
173    2
      ..
188    0
71     2
106    1
270    0
102    1
Name: target, Length: 240, dtype: Int64

In [11]:
client = bigquery.Client()

project_id = client.project
bq_dataset = 'iris_test'
bq_table = 'iris_data'

In [12]:
dataset_ref = bigquery.DatasetReference(project_id, bq_dataset)
table_ref = dataset_ref.table(bq_table)
table = bigquery.Table(table_ref)
iterable_table = client.list_rows(table).to_dataframe_iterable()

In [13]:
dfs = []
for row in iterable_table:
    dfs.append(row)

In [14]:
df = pd.concat(dfs, ignore_index=True)
del dfs

In [15]:
df

     sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  target
0                5.1             2.5              3.0             1.1       1
1                5.0             2.0              3.5             1.0       1
2                5.7             2.6              3.5             1.0       1
3                6.0             2.2              4.0             1.0       1
4                5.8             2.6              4.0             1.2       1
..               ...             ...              ...             ...     ...
295              4.7             3.2              1.3             0.2       0
296              5.5             3.5              1.3             0.2       0
297              4.4             3.0              1.3             0.2       0
298              4.4             3.2              1.3             0.2       0
299              5.4             3.9              1.3             0.4       0

[300 rows x 5 columns]

In [16]:
X_train, X_test, y_train, y_test = train_test_split(
    df.drop("target", axis=1),
    df["target"],
    test_size=0.2,
    random_state=42,
)

In [ ]:
X_train["target"] = y_train
X_test["target"] = y_test